name: NuGet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v2.0.1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: 'latest'
      - run: pwsh ./build-nuget.ps1
      - run: nuget push -src "https://www.nuget.org/api/v2/package" nupkg/DisCatSharp.ProjectTemplates.*
        shell: pwsh
