name: NuGet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
      - run: pwsh ./build-nuget.ps1
      - run: nuget push -src "https://www.nuget.org/api/v2/package" $(find . -name "*ProjectTemplates*.nupkg")
